#!/bin/sh

video_codec=libx264
audio_codec=libvorbis
movie=$1
density=$2
start=$3
stop=$4

if [[ "$movie" == "" ]]; then
    echo "
USAGE: vidls movie_file [frames_each_second [first_frame [last_frame]]]
"
    exit 1
fi
if [[ "$density" == "" ]];then
    density=2
fi

filter="fps=$density"

if [[ "$start" != "" ]]; then
    start_flag="-ss $start"
fi
if [[ "$stop" != "" ]]; then
    duration=$((stop-start))
    stop_flag="-t $duration"
fi

movie_name=$(basename $movie)
rm $movie_name-*.png
ffmpeg -i $movie -vf $filter $start_flag $stop_flag $movie_name-%5d.png

frames=$(echo $movie_name-*.png)
total_frames=$(echo $frames | wc -w)
current_frame=1
for frame in $frames
do
    convert -pointsize 50 label:"$current_frame / $total_frames" -gravity Center $frame -append $frame
    current_frame=$((current_frame+1))
done
