#!/bin/sh -e

do_math() {
    echo "scale=2;$@" | bc
}

video_codec=libx264
audio_codec=libvorbis
ffmpeg_filters="scale=640:-1"
pic_viewer=gpicview

movie=$(readlink -e $1)
density=$2
start=$3
stop=$4

if [[ "$movie" == "" ]]; then
    echo "
USAGE: vidls movie_file [frames_each_second [first_frame [last_frame]]]
"
    exit 1
fi
if [[ "$density" == "" ]];then
    density=2
fi

filter="fps=$density"
if [[ "$ffmpeg_filters" != "" ]];then
    filter="$ffmpeg_filters, $filter"
fi

if [[ "$start" != "" ]]; then
    start_flag="-ss $start"
fi
if [[ "$stop" != "" ]]; then
    duration=$(do_math $stop-$start)
    stop_flag="-t $duration"
fi

movie_name=$(basename $movie)

workdir=/tmp/vidls/$RANDOM
echo "frames generated to: $workdir"
mkdir -p $workdir
cd $workdir

ffmpeg -loglevel -8 -i $movie -vf "$filter" $start_flag $stop_flag $FFMPEG_FLAGS $movie_name-%5d.png

frames=$(echo $movie_name-*.png)
total_frames=$(echo $frames | wc -w)
current_frame=1
for frame in $frames
do
    echo "$current_frame / $total_frames"
    convert -pointsize 50 label:"$current_frame / $total_frames" -gravity Center $frame -append $frame
    current_frame=$(do_math $current_frame+1)
done | wait_nfo "$total_frames"

$pic_viewer .
