#!/bin/bash

encoding=utf8
temp='.vidsub'

do_math() {
    echo $@ | bc
}

get_time() {
    mplayer $@ -sub vid.srt -subcp $encoding 2> /dev/null \
    	| grep 'A:' \
    	| sed 's/.*A:\s*//' \
    	| sed 's/\s*V:.*//' \
    	| tail -n1 
}

hid_time() {
    seconds_full=$1
    frac=${seconds_full##*.}
    all_seconds=${seconds_full%.*}
    all_minutes=$(do_math $all_seconds/60)
    seconds=$(do_math $all_seconds%60)
    hours=$(do_math $all_minutes/60)
    minutes=$(do_math $all_minutes%60)

    printf '%02d:%02d:%02d,%d00' $hours $minutes $seconds $frac
}

last=0
seek_from=0

if [[ -f "$temp" ]]; then
    eval $(cat "$temp")
fi

subno=$((last+1))
start=$(get_time $@ -ss $seek_from)
end=$(get_time $@ -ss $start)

echo -e "$subno\n$(hid_time $start) --> $(hid_time $end)" >> vid.srt
echo -n "...: "
cat >> vid.srt
echo >> vid.srt

end=$(do_math $start-1)
echo -e "last=$subno\nseek_from=$end" > $temp
