#!/bin/sh

called_as=$0

usage() {
    echo "USAGE: $called_as cut_label"
    exit 1
}

[[ $# != 1 ]] && usage

cut_label=$1
eval $(vidcode $cut_label)

mplayer $source \
    $([[ ! -z "$start" ]] && echo "-ss $start") \
    $([[ ! -z "$duration" ]] && echo "-endpos $duration")\
    $([[ ! -z "$filters" ]] && echo "-vf $filters")
