#!/bin/sh -x

called_as=$0

command_line=$( \
    for label in $(grep -hP "^:" .vidkit-cuts | sed 's/^://')
    do
        eval $(vidcode $label)
        
        echo "$source"
        [[ ! -z "$start" ]] && echo "-ss $start"
        [[ ! -z "$duration" ]] && echo "-endpos $duration"
        [[ ! -z "$filters" ]] && echo "-vf $filters"
        [[ ! -z "$vfilters" ]] && echo "-vf $vfilters"
        [[ ! -z "$afilters" ]] && echo "-vf $afilters"

        [[ ! -z "$filters" ]] && echo "vidvid: WARNING filters parameter in vidkit-cuts is obsolete, for backward compatibility. Please change it to vfilters" 1>&2
    done 
)

mencoder $command_line -o vid.mp4 -oac lavc -ovc lavc
