#!/bin/sh -x

called_as=$0

command_line=$( \
    for label in $(grep -hP "^:" .vidkit-cuts | sed 's/^://')
    do
        eval $(vidcode $label)
        
        echo "$source"
        [[ ! -z "$start" ]] && echo "-ss $start"
        [[ ! -z "$duration" ]] && echo "-endpos $duration"
        [[ ! -z "$filters" ]] && echo "-vf $filters"
    done 
)

mencoder $command_line -o vid.mp4 -oac mp3lame -ovc x264
